### 新增用户
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "xiaohong",
  "password": "Test123456",
  "age": 19
}


### 禁用2号用户
PATCH http://localhost:8080/users/2/status?status=0
